apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: java-15-294 
  janus-idp.io/tekton: java-15-294
  backstage.io/kubernetes-id: java-15-294
  backstage.io/kubernetes-namespace: jkopriva 
  app.kubernetes.io/part-of: java-15-294
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml