apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: java-15-294
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-15-294 
  name: java-15-294
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: java-15-294 
